#pragma config(Motor,  port2,           rightfrontmotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightbackmotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightarmbar,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mobilegoal,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftarmbar,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftbackmotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftfrontmotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

int count = 0;
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
// Motor Grouping Functions
// These functions allow you to control a group of motors as one.

	// Set all drive motors
	void drive_forward()
{
	startMotor(rightfrontmotor, 127);
	startMotor(rightbackmotor, 127);
	startMotor(leftfrontmotor, 127);
	startMotor(leftbackmotor, 127);
}

	void drive_back()
{
	startMotor(rightfrontmotor, -127);
	startMotor(rightbackmotor, -127);
	startMotor(leftfrontmotor, -127);
	startMotor(leftbackmotor, -127);
}

	void stop_drive()
{
		stopMotor(rightfrontmotor);
		stopMotor(rightbackmotor);
		stopMotor(leftfrontmotor);
		stopMotor(leftbackmotor);
}

	void turn_left()
{
	startMotor(rightfrontmotor, 127);
	startMotor(rightbackmotor, 127);
	startMotor(leftfrontmotor, -127);
	startMotor(leftbackmotor, -127);
}

void turn_right()
{
	startMotor(rightfrontmotor, -127);
	startMotor(rightbackmotor, -127);
	startMotor(leftfrontmotor, 127);
	startMotor(leftbackmotor, 127);
}

void grab_cone()
{
	startMotor(claw, 127);
}

void drop_cone()
{
	startMotor(claw, -127);
}

void stop_claw()
{
	stopMotor (claw);
}

void lift_arm()
{
	startMotor(rightarmbar, 127);
	startMotor(leftarmbar, 127);
}

void drop_arm()
{
	startMotor(rightarmbar, -127);
	startMotor(leftarmbar, -127);
}

void stop_arm()
{
	stopMotor(rightarmbar);
	stopMotor(leftarmbar);
}

void mobilegoal_down()
{
	startMotor(mobilegoal, 127);
}

void mobilegoal_up()
{
	startMotor(mobilegoal, -127);
}

void stop_mobilegoal()
{
	stopMotor(mobilegoal);
}


void skillsAuton()
{

}

void StationaryAuton()
{
lift_arm();
	wait(4);
	stop_arm();
	wait(.1);
	drive_forward();
	wait(1.4);
	stop_drive();
	wait(.1);
	lift_arm();
	wait(.5);
	stop_arm();
	wait(.1);
	drop_arm();
	wait(1);
	stop_arm();
	wait(.1);
	drop_cone();
	wait(.1);
	stop_claw();
	wait(.1);
	lift_arm();
	wait(1);
	stop_arm();
	wait(.1);
	drive_back();
	wait(1);
	stop_drive();
	wait(.1);
	turn_right();
	wait(.5);
	stop_drive();
	wait(.1);
	drive_forward();
	wait(1);
	stop_drive();
	wait(.1);
}

void waitForPress()
{
  while(nLCDButtons == 0){}
  wait1Msec(5);
}
void waitForRelease()
{
  while(nLCDButtons != 0){}
  wait1Msec(5);
}
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
//Clear the LCD
  clearLCDLine(0);
  clearLCDLine(1);
  while(nLCDButtons != centerButton)
  {
    //Switch case that allows the user to choose from 3 different options
    switch(count){
    case 0:
      //Display first choice
      displayLCDCenteredString(0, "Stationary Auton");
      displayLCDCenteredString(1, "<     Enter    >");
      waitForPress();
      //Increment or decrement "count" based on button press
      if(nLCDButtons == leftButton)
      {
        waitForRelease();
        count = 2;
      }
      else if(nLCDButtons == rightButton)
      {
        waitForRelease();
        count++;
      }
      break;
    case 1:
      //Display second choice
      displayLCDCenteredString(0, "Right Auton");
      displayLCDCenteredString(1, "<     Enter    >");
      waitForPress();
      //Increment or decrement "count" based on button press
      if(nLCDButtons == leftButton)
      {
        waitForRelease();
        count--;
      }
      else if(nLCDButtons == rightButton)
      {
        waitForRelease();
        count++;
      }
      break;
    case 2:
      //Display third choice
      displayLCDCenteredString(0, "Skills");
      displayLCDCenteredString(1, "<     Enter    >");
      waitForPress();
      //Increment or decrement "count" based on button press
      if(nLCDButtons == leftButton)
      {
        waitForRelease();
        count--;
      }
      else if(nLCDButtons == rightButton)
      {
        waitForRelease();
        count = 0;
      }
      break;
    default:
      count = 0;
      break;
    }
  }

    string name = "";
    if(count==0){name="stationary Auton";}
    if(count==1){name="Right Auton";}
    if(count==2){name="Skills";}
  	displayLCDCenteredString(1, name);
  	displayLCDCenteredString(1, "<Cancel>");
  	delay(1000);
  	displayLCDCenteredString(0, "Robot Calibration");
  	displayLCDCenteredString(1, "<Running... 3s>");
		// Clear Gyro and Encoders
 		displayLCDCenteredString(1, "<Running... 1s>");
 		wait1Msec(1000);
  	displayLCDCenteredString(0, "Ready For Match!");
  	displayLCDCenteredString(1, "<Press to Cancel>");
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	switch(count)
	{
  case 0: // Left Autonomous
    displayLCDCenteredString(0, "Stationary Auto");
    displayLCDCenteredString(1, "<Running>");
    wait1Msec(1000);
   	StationaryAuton();
    break;
  case 1: // Right Autonomous
    displayLCDCenteredString(0, "Right Autonomous");
    displayLCDCenteredString(1, "<Running>");
    // Right Auton goes here
    break;
  case 2: // Skills Challenge
    displayLCDCenteredString(0, "Skills Challenge");
    displayLCDCenteredString(1, "<Running>");
    skillsAuton();
    break;
  default:


	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
     motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
    motor[leftbackmotor] = vexRT[Ch3];
    motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
    motor[rightbackmotor] = vexRT[Ch2];


    while (vexRT[Btn6U] == 1)
    {
	startMotor(leftarmbar, 127);
	startMotor(rightarmbar, 127);

    motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
    motor[leftbackmotor] = vexRT[Ch3];
    motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
    motor[rightbackmotor] = vexRT[Ch2];
  }
  stopMotor(leftarmbar);
  stopMotor(rightarmbar);
   stopMotor(mobilegoal);

       while (vexRT[Btn6D] == 1)
    {
	startMotor(leftarmbar, -127);
	startMotor(rightarmbar, -127);

    motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
    motor[leftbackmotor] = vexRT[Ch3];
    motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
    motor[rightbackmotor] = vexRT[Ch2];
  }
  stopMotor(leftarmbar);
  stopMotor(rightarmbar);
   stopMotor(mobilegoal);


  while (vexRT[Btn5U] == 1)
  {
	startMotor(mobilegoal, 127);


    motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
    motor[leftbackmotor] = vexRT[Ch3];
    motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
    motor[rightbackmotor] = vexRT[Ch2];
}
  stopMotor(leftarmbar);
  stopMotor(rightarmbar);
   stopMotor(mobilegoal);

	  while (vexRT[Btn5D] == 1)
  {
	startMotor(mobilegoal, -127);


    motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
    motor[leftbackmotor] = vexRT[Ch3];
    motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
    motor[rightbackmotor] = vexRT[Ch2];
}
  stopMotor(leftarmbar);
  stopMotor(rightarmbar);
   stopMotor(mobilegoal);

	  while (vexRT[Btn8U] == 1)
  {
	startMotor(claw, 127);


    motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
    motor[leftbackmotor] = vexRT[Ch3];
    motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
    motor[rightbackmotor] = vexRT[Ch2];
}
stopMotor(claw);

	  while (vexRT[Btn8D] == 1)
  {
	startMotor(claw, -127);


    motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
    motor[leftbackmotor] = vexRT[Ch3];
    motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
    motor[rightbackmotor] = vexRT[Ch2];
}
stopMotor(claw);
}
}
