#pragma config(Motor,  port2,           rightfrontmotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightbackmotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           fourbar,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mobilegoal,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           chainbar,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftbackmotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftfrontmotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

int count = 0;
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
// Motor Grouping Functions
// These functions allow you to control a group of motors as one.

// Set all drive motors

void ResetDriveEncoder()
{

}
void drive_forward()
{
	startMotor(rightfrontmotor, 127);
	startMotor(rightbackmotor, 127);
	startMotor(leftfrontmotor, 127);
	startMotor(leftbackmotor, 127);
}

void drive_back()
{
	startMotor(rightfrontmotor, -127);
	startMotor(rightbackmotor, -127);
	startMotor(leftfrontmotor, -127);
	startMotor(leftbackmotor, -127);
}

void stop_drive()
{
	stopMotor(rightfrontmotor);
	stopMotor(rightbackmotor);
	stopMotor(leftfrontmotor);
	stopMotor(leftbackmotor);
}

void turn_left()
{
	startMotor(rightfrontmotor, 127);
	startMotor(rightbackmotor, 127);
	startMotor(leftfrontmotor, -127);
	startMotor(leftbackmotor, -127);
}

void turn_right()
{
	startMotor(rightfrontmotor, -127);
	startMotor(rightbackmotor, -127);
	startMotor(leftfrontmotor, 127);
	startMotor(leftbackmotor, 127);
}

void grab_cone()
{
	startMotor(claw, 127);
}

void drop_cone()
{
	startMotor(claw, -127);
}

void stop_claw()
{
	stopMotor (claw);
}

void lift_arm()
{
	startMotor(fourbar, 100);
}

void drop_arm()
{
	startMotor(fourbar, -100);
}

void stop_arm()
{
	stopMotor(fourbar);
}

void chain_forward()
{
	startMotor(chainbar, 100);
}

void chain_back()
{
	startMotor(chainbar, -100);
}

void stop_chain()
{
	stopMotor(chainbar);
}

void mobilegoal_down()
{
	startMotor(mobilegoal, 127);
}

void mobilegoal_up()
{
	startMotor(mobilegoal, -127);
}

void stop_mobilegoal()
{
	stopMotor(mobilegoal);
}
void RedMobile()
{
	drive_forward();
	chain_back();
	wait1Msec(1500);
	stop_drive();
	stop_chain();
	wait1Msec(100);
	mobilegoal_down();
	wait1Msec(1500);
	stop_mobilegoal();
	wait1Msec(100);
	drive_forward();
	wait1Msec(1000);
	stop_drive();
	wait1Msec(100);
	mobilegoal_up();
	chain_forward();
	wait1Msec(1500);
	stop_mobilegoal();
	stop_chain();
	wait1Msec(100);
	drop_cone();
	wait1Msec(500);
	stop_claw();
	wait1Msec(100);
	drive_back();
	chain_back();
	wait1Msec(1000);
	turn_right();
	wait1Msec(1200);
	stop_drive();
	wait1Msec(100);
	drive_forward();
	wait1Msec(1000);
	stop_drive();
	wait1Msec(100);
	mobilegoal_down();
	wait1Msec(800);
	drive_back();
	wait1Msec(1000);
}
void BlueMobile()
{
	drive_forward();
	chain_back();
	wait1Msec(1500);
	stop_drive();
	stop_chain();
	wait1Msec(100);
	mobilegoal_down();
	wait1Msec(1500);
	stop_mobilegoal();
	wait1Msec(100);
	drive_forward();
	wait1Msec(1000);
	stop_drive();
	wait1Msec(100);
	mobilegoal_up();
	chain_forward();
	wait1Msec(1500);
	stop_mobilegoal();
	stop_chain();
	wait1Msec(100);
	drop_cone();
	wait1Msec(500);
	stop_claw();
	wait1Msec(100);
	drive_back();
	chain_back();
	wait1Msec(1000);
	turn_left();
	wait1Msec(1200);
	stop_drive();
	wait1Msec(100);
	drive_forward();
	wait1Msec(1000);
	stop_drive();
	wait1Msec(100);
	mobilegoal_down();
	wait1Msec(800);
	drive_back();
	wait1Msec(1000);
}
void skillsAuton()
{

}

void StationaryAuton()
{

}
void checkbattery()
{
	bLCDBacklight = true;									// Turn on LCD Backlight
	string mainBattery, backupBattery;

	clearLCDLine(0);											// Clear line 1 (0) of the LCD
	clearLCDLine(1);											// Clear line 2 (1) of the LCD

	//Display the Primary Robot battery voltage
	displayLCDString(0, 0, "Primary: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
	displayNextLCDString(mainBattery);

	//Display the Backup battery voltage
	displayLCDString(1, 0, "Backup: ");
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
	displayNextLCDString(backupBattery);
}
void Legends()
{
	bLCDBacklight = true;
	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDCenteredString(0, "Legends");
	displayLCDCenteredString(1, "Waiting...");
}
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	//Clear the LCD
	clearLCDLine(0);
	clearLCDLine(1);
	while(nLCDButtons != centerButton)
	{
		//Switch case that allows the user to choose from 3 different options
		switch(count){
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "Stationary Auton");
			displayLCDCenteredString(1, "<     Enter    >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 2;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 1:
			//Display second choice
			displayLCDCenteredString(0, "Red Mobile");
			displayLCDCenteredString(1, "<     Enter    >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
			case 2:
			// display
			displayLCDCenteredString(0, "Blue Mobile");
			displayLCDCenteredString(1, "<    Enter    >");
			waitForPress();
			// increment
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if (nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;   // <----- might need to change to count = 0;
			}
			break;

		case 3:
			//Display third choice
			displayLCDCenteredString(0, "Skills");
			displayLCDCenteredString(1, "<     Enter    >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;
		case 4:
			//Display third choice
			displayLCDCenteredString(0, "Legends");
			displayLCDCenteredString(1, "<     Enter    >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;
		default:
			count = 0;
			break;
		}
	}

	string name = "";
	if(count==0){name="Stationary Auton";}
	if(count==1){name="Red Mobile";}
	if(count==2){name="Blue Mobile";}
	if(count==3){name="Skills";}
	if(count==4){name="Legends";}
	displayLCDCenteredString(1, name);
	displayLCDCenteredString(1, "<Cancel>");
	delay(1000);
	displayLCDCenteredString(0, "Robot Calibration");
	displayLCDCenteredString(1, "<Running... 3s>");
	wait1Msec(1000);
	// Clear Gyro and Encoders
	displayLCDCenteredString(1, "<Running... 2s>");
	ResetDriveEncoder();
	wait(1000);
	//Final preperations
	displayLCDCenteredString(1, "<Running... 1s>");
	wait1Msec(1000);
	displayLCDCenteredString(0, "Ready For Match!");
	displayLCDCenteredString(1, "<Press to Cancel>");
	bStopTasksBetweenModes = true; // might have to swith to false ------------------------------------------------------------------------

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	switch(count)
	{
	case 0: // Left Autonomous
		displayLCDCenteredString(0, "Stationary Auto");
		displayLCDCenteredString(1, "<Running>");
		wait1Msec(1000);
		StationaryAuton();
		break;
	case 1: // Right Autonomous
		displayLCDCenteredString(0, "Red Mobile Auto");
		displayLCDCenteredString(1, "<Running>");
		wait1Msec(1000);
		RedMobile();
		break;
	case 2: // Blue mobile
		displayLCDCenteredString(0, "Blue Mobile Auto");
		displayLCDCenteredString(1, "<Running>");
		wait1Msec(1000);
		BlueMobile();
		break;
	case 3: // Skills Challenge
		displayLCDCenteredString(0, "Skills Challenge");
		displayLCDCenteredString(1, "<Running>");
		skillsAuton();
		break;
	case 4: // Legends
		displayLCDCenteredString(0, "Legends");
		displayLCDCenteredString(1, "<Running>");
		Legends();
	default:


	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
		motor[leftbackmotor] = vexRT[Ch3];
		motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
		motor[rightbackmotor] = vexRT[Ch2];
		motor[fourbar] = vexRT[Ch3Xmtr2];

		if (vexRT[Btn6UXmtr2] == 1)   // lift the 4 bar lift
		{
			startMotor(chainbar, -70);

			motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
			motor[leftbackmotor] = vexRT[Ch3];
			motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
			motor[rightbackmotor] = vexRT[Ch2];
			motor[fourbar] = vexRT[Ch3Xmtr2];
		}
		else   // stop 4 bar lift
		{
			stopMotor(chainbar);

			motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
			motor[leftbackmotor] = vexRT[Ch3];
			motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
			motor[rightbackmotor] = vexRT[Ch2];
			motor[fourbar] = vexRT[Ch3Xmtr2];
		}

		if (vexRT[Btn6DXmtr2] == 1)   // bring down 4 bar
		{
			startMotor(claw, 127);

			motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
			motor[leftbackmotor] = vexRT[Ch3];
			motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
			motor[rightbackmotor] = vexRT[Ch2];
			motor[fourbar] = vexRT[Ch3Xmtr2];
		}
		else   // stop 4 bar
		{
			stopMotor(claw);

			motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
			motor[leftbackmotor] = vexRT[Ch3];
			motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
			motor[rightbackmotor] = vexRT[Ch2];
			motor[fourbar] = vexRT[Ch3Xmtr2];
		}


		if (vexRT[Btn5UXmtr2] == 1)   // bring forward chain bar
		{
			startMotor(chainbar, 70);

			motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
			motor[leftbackmotor] = vexRT[Ch3];
			motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
			motor[rightbackmotor] = vexRT[Ch2];
			motor[fourbar] = vexRT[Ch3Xmtr2];
		}
		else   // stop chain bar
		{
			stopMotor(chainbar);

			motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
			motor[leftbackmotor] = vexRT[Ch3];
			motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
			motor[rightbackmotor] = vexRT[Ch2];
			motor[fourbar] = vexRT[Ch3Xmtr2];
		}

		if (vexRT[Btn5DXmtr2] == 1)   // bring chain bar back
		{
			startMotor(claw, -127);

			motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
			motor[leftbackmotor] = vexRT[Ch3];
			motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
			motor[rightbackmotor] = vexRT[Ch2];
			motor[fourbar] = vexRT[Ch3Xmtr2];
		}
		else // stop chain bar
		{
			stopMotor(claw);

			motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
			motor[leftbackmotor] = vexRT[Ch3];
			motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
			motor[rightbackmotor] = vexRT[Ch2];
			motor[fourbar] = vexRT[Ch3Xmtr2];
		}


		if (vexRT[Btn5U] == 1) // raise mobile goal lift
		{
			startMotor(mobilegoal, 127);

			motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
			motor[leftbackmotor] = vexRT[Ch3];
			motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
			motor[rightbackmotor] = vexRT[Ch2];
			motor[fourbar] = vexRT[Ch3Xmtr2];
		}
		else   // stop mobile goal lift
		{
			stopMotor(mobilegoal);

			motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
			motor[leftbackmotor] = vexRT[Ch3];
			motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
			motor[rightbackmotor] = vexRT[Ch2];
			motor[fourbar] = vexRT[Ch3Xmtr2];
		}

		if (vexRT[Btn5D] == 1)
		{
			startMotor(mobilegoal, -127);

			motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
			motor[leftbackmotor] = vexRT[Ch3];
			motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
			motor[rightbackmotor] = vexRT[Ch2];
			motor[fourbar] = vexRT[Ch3Xmtr2];
		}
		else
		{
			stopMotor(mobilegoal);

			motor[leftfrontmotor]  = vexRT[Ch3];   // Left Joystick Y value
			motor[leftbackmotor] = vexRT[Ch3];
			motor[rightfrontmotor] = vexRT[Ch2];   // Right Joystick Y value
			motor[rightbackmotor] = vexRT[Ch2];
			motor[fourbar] = vexRT[Ch3Xmtr2];
		}

		if (vexRT[Btn7U] == 1)
		{
			checkbattery();
		}
	}
}
