#pragma config(Motor,  port2,           rightfrontmotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightbackmotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightarmbar,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mobilegoal,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftarmbar,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftbackmotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftfrontmotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void drive_forward()
{
	startMotor(rightfrontmotor, 127);
	startMotor(rightbackmotor, 127);
	startMotor(leftfrontmotor, 127);
	startMotor(leftbackmotor, 127);
}

void drive_back()
{
	startMotor(rightfrontmotor, -127);
	startMotor(rightbackmotor, -127);
	startMotor(leftfrontmotor, -127);
	startMotor(leftbackmotor, -127);
}

void stop_drive()
{
	stopMotor(rightfrontmotor);
	stopMotor(rightbackmotor);
	stopMotor(leftfrontmotor);
	stopMotor(leftbackmotor);
}

void turn_left()
{
	startMotor(rightfrontmotor, 127);
	startMotor(rightbackmotor, 127);
	startMotor(leftfrontmotor, -127);
	startMotor(leftbackmotor, -127);
}

void turn_right()
{
	startMotor(rightfrontmotor, -127);
	startMotor(rightbackmotor, -127);
	startMotor(leftfrontmotor, 127);
	startMotor(leftbackmotor, 127);
}

void grab_cone()
{
	startMotor(claw, 127);
}

void drop_cone()
{
	startMotor(claw, -127);
}

void stop_claw()
{
	stopMotor (claw);
}

void lift_arm()
{
	startMotor(rightarmbar, 127);
	startMotor(leftarmbar, 127);
}

void drop_arm()
{
	startMotor(rightarmbar, -127);
	startMotor(leftarmbar, -127);
}

void stop_arm()
{
	stopMotor(rightarmbar);
	stopMotor(leftarmbar);
}

void mobilegoal_down()
{
	startMotor(mobilegoal, 127);
}

void mobilegoal_up()
{
	startMotor(mobilegoal, -127);
}

void stop_mobilegoal()
{
	stopMotor(mobilegoal);
}
void RedMobile()
{

}
void BlueMobile()
{

}
void skillsAuton()
{

}

void StationaryAuton()
{
	lift_arm();
	wait1Msec(2500);
	stop_arm();
	wait1Msec(100);
	drive_forward();
	wait1Msec(1000);
	stop_drive();
	wait1Msec(100);
	drop_arm();
	wait1Msec(500);
	stop_arm();
	wait1Msec(100);
	drop_cone();
	wait1Msec(500);
	stop_claw();
	wait1Msec(100);
	lift_arm();
	wait1Msec(1000);
	drive_back();
	wait1Msec(1000);
	stop_drive();
	wait1Msec(100);

}

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	StationaryAuton();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		motor[leftbackmotor] = vexRT[Ch3];
		motor[leftfrontmotor] = vexRT[Ch3];
		motor[rightbackmotor] = vexRT[Ch2];
		motor[rightfrontmotor] = vexRT[Ch2];
		motor[claw] = vexRT[Ch2Xmtr2];

		if(vexRT[Btn6UXmtr2] == 1)
		{
			startMotor(leftarmbar, 127);
			startMotor(rightarmbar, 127);

			motor[leftbackmotor] = vexRT[Ch3];
			motor[leftfrontmotor] = vexRT[Ch3];
			motor[rightbackmotor] = vexRT[Ch2];
			motor[rightfrontmotor] = vexRT[Ch2];
			motor[claw] = vexRT[Ch2Xmtr2];
		}
		else
		{
			stopMotor(leftarmbar);
			stopMotor(rightarmbar);

			motor[leftbackmotor] = vexRT[Ch3];
			motor[leftfrontmotor] = vexRT[Ch3];
			motor[rightbackmotor] = vexRT[Ch2];
			motor[rightfrontmotor] = vexRT[Ch2];
			motor[claw] = vexRT[Ch2Xmtr2];
		}

		if(vexRT[Btn6DXmtr2] == 1)
		{
			startMotor(leftarmbar, -127);
			startMotor(rightarmbar, -127);

			motor[leftbackmotor] = vexRT[Ch3];
			motor[leftfrontmotor] = vexRT[Ch3];
			motor[rightbackmotor] = vexRT[Ch2];
			motor[rightfrontmotor] = vexRT[Ch2];
			motor[claw] = vexRT[Ch2Xmtr2];
		}
		else
		{
			stopMotor(leftarmbar);
			stopMotor(rightarmbar);

			motor[leftbackmotor] = vexRT[Ch3];
			motor[leftfrontmotor] = vexRT[Ch3];
			motor[rightbackmotor] = vexRT[Ch2];
			motor[rightfrontmotor] = vexRT[Ch2];
			motor[claw] = vexRT[Ch2Xmtr2];
		}

		if(vexRT[Btn5UXmtr2] == 1)
		{
			startMotor(mobilegoal, 127);

			motor[leftbackmotor] = vexRT[Ch3];
			motor[leftfrontmotor] = vexRT[Ch3];
			motor[rightbackmotor] = vexRT[Ch2];
			motor[rightfrontmotor] = vexRT[Ch2];
			motor[claw] = vexRT[Ch2Xmtr2];
		}
		else
		{
			stopMotor(mobilegoal);

			motor[leftbackmotor] = vexRT[Ch3];
			motor[leftfrontmotor] = vexRT[Ch3];
			motor[rightbackmotor] = vexRT[Ch2];
			motor[rightfrontmotor] = vexRT[Ch2];
			motor[claw] = vexRT[Ch2Xmtr2];
		}

		if(vexRT[Btn5DXmtr2] == 1)
		{
			startMotor(mobilegoal, -127);

			motor[leftbackmotor] = vexRT[Ch3];
			motor[leftfrontmotor] = vexRT[Ch3];
			motor[rightbackmotor] = vexRT[Ch2];
			motor[rightfrontmotor] = vexRT[Ch2];
			motor[claw] = vexRT[Ch2Xmtr2];
		}
		else
		{
			stopMotor(mobilegoal);

			motor[leftbackmotor] = vexRT[Ch3];
			motor[leftfrontmotor] = vexRT[Ch3];
			motor[rightbackmotor] = vexRT[Ch2];
			motor[rightfrontmotor] = vexRT[Ch2];
			motor[claw] = vexRT[Ch2Xmtr2];
		}
	}
}
